version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db_sub_base_2_1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "11433:5433"
    volumes:
      - ./backend/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - postgres_data_sub_base_2_1:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build:
      context: ./backend
    container_name: app_sub_api_1
    depends_on:
      - db
    environment:
      - SSL=${SSL}
      - PORT=${PORT}
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    ports:
      - "12443:7000"
    volumes:
      - ./backend/certs:/app_sub_api_1/certs
      - ./backend/initiation.sql:/docker-entrypoint-initdb.d/initiation.sql
    command: >
      sh -c "sleep 10 && 
      PGPASSWORD=${POSTGRES_PASSWORD} psql -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /docker-entrypoint-initdb.d/initiation.sql && 
      npm start"

  frontend:
    build:
      context: ./frontend
    container_name: sub_frontend_1
    ports:
      - "13173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    depends_on:
      - app
    env_file:
      - ./frontend/.env

volumes:
  postgres_data_sub_base_2_1:

networks:
  shared_network:
    external: true